name: Finalize Build and Pass Workflow

on:
  workflow_call:
    inputs:
      BUILD_VARS_JSON:
        required: true
        type: string
    secrets:
      GIT_ACTIONS:
        required: true

jobs:
  finalize_build:
    runs-on: ubuntu-latest
    steps:

      - name: Delete current repo from build_vars.json
        id: modify_json
        run: |
          modified_json=$(echo "${{ inputs.BUILD_VARS_JSON }}" | jq 'del(.repos[0])')
          echo "BUILD_VARS_JSON=$modified_json" >> $GITHUB_ENV
          echo "::set-output name=BUILD_VARS_JSON::$modified_json"

      - name: Look up NEXTREPO
        id: extract_repo_name
        run: |
          NEXTREPO=$(echo "${{ steps.modify_json.outputs.BUILD_VARS_JSON }}" | jq -r '.repos[0].name')
          echo "NEXTREPO=$NEXTREPO" >> $GITHUB_ENV

      - name: Add GitHub Run ID to buildids
        id: add_run_id
        run: |
          GITHUB_RUN_ID=${{ github.run_id }}
          updated_json=$(echo "${{ steps.modify_json.outputs.BUILD_VARS_JSON }}" | jq --arg run_id "$GITHUB_RUN_ID" '.buildids."${{ github.event.repository.name }}" = $run_id')
          echo "BUILD_VARS_JSON=$updated_json" >> $GITHUB_ENV
          echo "::set-output name=BUILD_VARS_JSON::$updated_json"

      - name: Capture end date and time
        id: end_time
        run: echo "end_time=$(date -u)" >> $GITHUB_ENV

      - name: Add end time to build_vars.json
        id: final_update
        run: |
          final_json=$(echo "${{ steps.add_run_id.outputs.BUILD_VARS_JSON }}" | jq '.buildstats += { "${{ github.event.repository.name }}-end": "${{ env.end_time }}" }')
          echo "BUILD_VARS_JSON=$final_json" >> $GITHUB_ENV
          echo "::set-output name=BUILD_VARS_JSON::$final_json"

      - name: Trigger Next Repo Workflow
        if: ${{ env.BUILD_TYPE == 'FULL' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GIT_ACTIONS }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'cs1867',
              repo: '${{ env.NEXTREPO }}',
              workflow_id: '${{ env.NEXTREPO }}-workflow.yml',
              ref: 'github-workflow',
              inputs: {
                BUILD_VARS_JSON: '${{ env.BUILD_VARS_JSON }}'
              }
            })
