name: Main Workflow

on:
  push:  
    branches: [ 'master' ]

jobs:
  call-reusable:
    uses: cs1867/project/.github/workflows/reusable.yml
    with:
      input_string: "Dogs"

  show-result:
    runs-on: ubuntu-latest
    needs: call-reusable
    steps:
      - run: |
         echo "Final Result: ${{ needs.call-reusable.outputs.result }}"
