name: Main Workflow

on:
  push:  
    branches: [ 'master' ]
    
env: 
  RUN_ID: ${{ github.run_id }} 
  BUILD_BRANCH: '5.2.0'
  BUILD_TYPE: 'FULL'
  BUILD_REPO: 'nightly'
  BUILD_OS: 'el8'
  
  
jobs:

  set-vars:
    runs-on: ubuntu-latest
    outputs:
      animal: ${{ steps.set.outputs.animal }}
      build_os: ${{ steps.set.outputs.build_os }}
      
    steps:
      - id: set
        run: echo "animal=Dogs" >> $GITHUB_OUTPUT
             echo "build_os=el8" >> $GITHUB_OUTPUT
             
  call-reusable:
    uses: cs1867/project/.github/workflows/reuseable.yml@master
    needs: set-vars
    with:
      input_string: ${{ needs.set-vars.outputs.animal }}
      buildos_string: ${{ needs.set-vars.outputs.build_os }}

  show-result:
    runs-on: ubuntu-latest
    needs: call-reusable
    steps:
      - run: |
         echo "Final Result: ${{ needs.call-reusable.outputs.result }}"
