name: Main Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable:
    uses: cs1867/project/.github/workflows/reuseable.yml@master
    with:
      input_string: "Dogs"

  show-result:
    runs-on: ubuntu-latest
    needs: call-reusable
    steps:
      - run: |
         echo "Final Result: ${{ needs.call-reusable.outputs.result }}"
