name: Main Workflow

on:
  push:
    branches: [ 'master' ]

jobs:
  call-reusable:
    uses:  cs1867/project/.github/.github/workflows/reusable.yml@master
    with:
      input_number: 1

  show-result:
    runs-on: ubuntu-latest
    needs: call-reusable
    steps:
      - run: |
         echo "Result from reusable workflow: ${{ needs.call-reusable.outputs.result }}"
