name: oneshot-script-build

on: 
  workflow_call:
    inputs:
      BUILD_VARS_JSON:
        required: true
        type: string
      BUILD_OS:
        required: true
        type: string
      BUILD_TYPE:
        required: true
        type: string
      BUILD_BRANCH:
        required: true
        type: string  

jobs:
  prep-build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Show variables
        run: |
          echo "BUILD_OS: ${{ inputs.BUILD_OS }}"
          echo "BUILD_TYPE: ${{ inputs.BUILD_TYPE }}"
          echo "BUILD_BRANCH: ${{ inputs.BUILD_BRANCH }}"
          echo "JSON: ${{ inputs.BUILD_VARS_JSON }}"  
          
      - name: Check out Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.BUILD_BRANCH }}
          
      - name: Create a temporary artifact downloads folder
        run: mkdir aritfacts
        
      - name: Extract dependencies
        id: extract_deps
        run: |
         echo '${{ inputs.BUILD_VARS_JSON }}' > input.json
         REPO_NAME="${{ github.event.repository.name }}"
         cat input.json | jq -r ".repos[] | select(.name == \"${REPO_NAME}\") | .deps[]" > deps.txt
         echo "Dependencies:"
         cat deps.txt
            
            
      - name: Download artifacts
        run: |
            mkdir -p artifacts
            while IFS= read -r repo; do
              echo "Downloading artifact for $repo"
              run_id=$(echo ${{ inputs.BUILD_VARS_JSON }} | jq -r ".buildids | .[\"$repo\"]")
              echo "rund id $run_id"
              gh run download $run_id --repo cs1867/$repo -D artifacts/$repo --name "$repo-${{ inputs.BUILD_OS }}"  
              artifact_path="artifacts/$repo"
              echo "list artifact path"
              ls -al "$artifact_path"
              case "${{ inputs.BUILD_OS }}" in
                'ol8'|'el9')
                  mkdir -p artifacts/RPMS
                  echo "copy to the artifacts RPM dir"
                  cp "$artifact_path"/RPMS/*.rpm artifacts/RPMS
                 ;;
                'd11'|'d12'|'u20'|'u22'|'u24')                
                  mkdir -p artifacts/DEBS
                  echo "copy to the artifacts DEBS dir"
                  cp -r "$artifact_path"/* artifacts/DEBS
                  echo "list artifacts DEBS dir"
                  ls -al artifacts/DEBS/*
                  ;;
              esac
            done < deps.txt
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS }}

      - name: run docker oneshot builder and github-actions-workflow.sh
        run: |
              case "${{ inputs.BUILD_OS }}" in
                'ol8'|'el9')              
                   curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build | sh -s - --run github-el-workflow.sh . '${{ inputs.BUILD_OS }}'  
                ;;
                'd11'|'d12'|'u20'|'u22'|'u24')                
                  curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build | sh -s - --run github-db-workflow.sh . '${{ inputs.BUILD_OS }}'
                ;;
              esac
      
      #- uses: actions/upload-artifact@v4
      #  with:
      #     name: ${{ github.event.repository.name }}-${{ inputs.BUILD_OS }}
      #     path: unibuild-repo
      #     retention-days: 5
       
