name: oneshot-build

on: 
  workflow_call:
    inputs:
      BUILD_VARS_JSON:
        required: true
        type: string
      BUILD_OS:
        required: true
        type: string
      BUILD_TYPE:
        required: true
        type: string
      BUILD_BRANCH:
        required: true
        type: string  

jobs:
  prep-build:
    runs-on: ubuntu-latest
      
    steps:
          
      - name: Check out Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.call-reusable.outputs.BUILD_BRANCH }}
          
      - name: Create a temporary artifact downloads folder
        run: mkdir aritfacts

      - name: run docker oneshot builder
        run: |
          curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build | sh -s - . '${{ needs.call-reusable.outputs.BUILD_OS }}'  
          
      - uses: actions/upload-artifact@v4
        with:
           name: ${{ github.event.repository.name }}-${{ needs.call-reusable.outputs.BUILD_OS }}
           path: unibuild-repo
           retention-days: 5
       
