name: oneshot-signer-test
 
on: 
  push:   
    branches: [ 'github-workflow' ]   
env: 
  RUN_ID: ${{ github.run_id }} 
  BUILD_BRANCH: '5.2.0'
  BUILD_TYPE: 'FULL'
  BUILD_REPO: 'nightly'
 
jobs:
       
  build-project:

 
    runs-on: ubuntu-latest

    steps:
            
        - name: Check out Repo
          uses: actions/checkout@v4  
          
        - name: Fetch workflow script from projects
          env:
             github-token: ${{ secrets.GIT_ACTIONS }}
          run: |
            git clone https://github.com/cs1867/project.git project
            cp project/toolbox/workflows/create-el-repo.sh .
         
        - name: Download artifacts
          run: |
            mkdir -p artifacts
             
              echo "Downloading artifact for i2util"
              run_id=16295432359
              echo "rund id $run_id"
              gh run download $run_id --repo cs1867/i2util -D artifacts/i2util --name "i2util-el9" 
              artifact_path="artifacts/i2util"
              pwd 
              echo "list artifact path"
              ls -al "$artifact_path"
              mkdir -p artifacts/RPMS
              echo "copy to the artifacts RPM dir"
              cp "$artifact_path"/RPMS/*.rpm artifacts/RPMS
          env:
            GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS }}

        - name: list files
          run: |      
            pwd
            echo "list artifacts dir"
            ls -al artifacts
            echo "list artifacts RPM dir"
            ls -al artifacts/RPMS
       # - name: Sign RPMs using docker-oneshot-signer
       #   run: |
       #     echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
       #     echo "${{ secrets.GPG_PASSPHRASE }}" > passphrase.txt
       #     chmod 600 private.key passphrase.txt
       #     ls -l private.key passphrase.txt
       #     pwd
       #     echo "===> Check private.key format"
       #     head -n 5 private.key

        #    echo "===> Check passphrase file"
        #    cat passphrase.txt | wc -c

           # curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-signer/main/sign \
           #   | sh -s - --passphrase "$(cat passphrase.txt)" artifacts/RPMS private.key

           # echo "Verifying signed RPMs..."
           # rpm --checksig artifacts/RPMS/*.rpm || true
           # gpg --list-keys
           # rpm --checksig artifacts/RPMS/*.rpm

       # - uses: actions/upload-artifact@v4
       #   with:
       #    name: ${{ github.event.repository.name }}-${{ env.BUILD_OS }}
       #    path: artifacts
       #    retention-days: 5
           
     
