name: oneshot-build

on: 
  workflow_call:
    inputs:
      BUILD_VARS_JSON:
        required: true
        type: string
    outputs: 
      BUILD_OS:
        description: "Build OS"
        value: ${{ jobs.prep-build.outputs.BUILD_OS }} 
      BUILD_BRANCH:
        description: "BUILD BRANCH"
        value: ${{ jobs.prep-build.outputs.BUILD_BRANCH }}
      BUILD_TYPE:
        description: "BUILD TYPE"
        value: ${{ jobs.prep-build.outputs.BUILD_TYPE }}
      BUILD_VARS_JSON:
        description: "BUILD JSON FILE"
        value: ${{ jobs.prep-build.outputs.BUILD_VARS_JSON }}

jobs:
  prep-build:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.add.outputs.result }}
      BUILD_OS: ${{ steps.extract-build-vars.outputs.BUILD_OS }}
      BUILD_BRANCH: ${{ steps.extract-build-vars.outputs.BUILD_BRANCH }}
      BUILD_TYPE: ${{ steps.extract-build-vars.outputs.BUILD_TYPE }}
      BUILD_VARS_JSON: ${{ steps.modify_json.outputs.BUILD_VARS_JSON }}
      
    steps:
          
      - name: Check out Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.call-reusable.outputs.BUILD_BRANCH }}
          
      - name: Create a temporary artifact downloads folder
        run: mkdir aritfacts

      - name: run docker oneshot builder
        run: |
          curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build | sh -s - . '${{ needs.call-reusable.outputs.BUILD_OS }}'  
          
      - uses: actions/upload-artifact@v4
        with:
           name: ${{ github.event.repository.name }}-${{ needs.call-reusable.outputs.BUILD_OS }}
           path: unibuild-repo
           retention-days: 5
       
