name: post-build

on: 
  workflow_call:
    inputs:
      BUILD_VARS_JSON:
        required: true  
        type: string
      BUILD_OS:
        required: true 
        type: string 
      BUILD_TYPE:
        required: true
        type: string
      BUILD_BRANCH:
        required: true
        type: string
    outputs: 
      NEXTREPO:
        description: "Next repo to build"
        value: ${{ jobs.post-build.outputs.NEXTREPO }}
      BUILD_VARS_JSON:
        description: "BUILD JSON FILE"
        value: ${{ jobs.psot-build.outputs.BUILD_VARS_JSON }}

jobs:
  post-build:
    runs-on: ubuntu-latest
    outputs:
      BUILD_VARS_JSON: ${{ steps.modify_json.outputs.BUILD_VARS_JSON }}
      NEXTREPO: ${{ steps.extract_repo_name.outputs.NEXTREPO }}
      
    steps:
      - name: Show variables
        run: |
          echo "BUILD_OS: ${{ inputs.BUILD_OS }}"
          echo "BUILD_TYPE: ${{ inputs.BUILD_TYPE }}"
          echo "BUILD_BRANCH: ${{ inputs.BUILD_BRANCH }}"
          echo "BUILD_VARS_JSON: ${{ inputs.BUILD_VARS_JSON }}"  


      -  name: Look up the next repo name to build
         id: extract_repo_name
         run: |
          echo "BUILD_VARS_JSON value is:"
          echo '${{ inputs.BUILD_VARS_JSON }}'
          NEXTREPO=$(echo '${{ inputs.BUILD_VARS_JSON }}' | jq -r '.repos[0].name')
          echo "NEXTREPO=$NEXTREPO" >> $GITHUB_OUTPUT
          echo "NEXTREPO=$NEXTREPO"

 

      - name: Add end time
        id: modify_json
        run: |
         REPO_NAME=${{ github.event.repository.name }}
         END_TIME=$(date -u)
         echo '${{ inputs.BUILD_VARS_JSON }}' > input.json
         modified_json=$(jq --arg key "${REPO_NAME}-end" --arg value "$END_TIME" '.buildstats[$key] = $value' input.json)
         BUILD_VARS_JSON=$(echo "$modified_json" | jq -c '.')

         echo "BUILD_VARS_JSON=$BUILD_VARS_JSON" >> $GITHUB_OUTPUT
         echo "**** next next ****"
         echo "BUILD_VARS_JSON=$BUILD_VARS_JSON"
         
     # - name: Pass workflow  
     #   if: inputs.BUILD_TYPE  == 'FULL'
     #   uses: actions/github-script@v6
     #   with:
     #     github-token: ${{secrets.GIT_ACTIONS }}
     #     script: |
     #       await github.rest.actions.createWorkflowDispatch({
     #         owner: 'cs1867',
     #         repo: '${{ env.NEXTREPO}}',
     #         workflow_id: '${{ env.NEXTREPO}}-workflow.yml',
     #         ref: 'github-workflow',
     #         inputs: {
     #           BUILD_VARS_JSON: '${{ inputs.BUILD_VARS_JSON }}'
     #         }
     #       })
