name: Pre Build Setup

on:
  workflow_call:
    inputs:
      BUILD_VARS_JSON:
        required: true
        type: string
    secrets:
      GIT_ACTIONS:
        required: true

jobs:
  pre_build_setup:
    runs-on: ubuntu-latest
    outputs:
      BUILD_VARS_JSON: ${{ steps.set_outputs.outputs.BUILD_VARS_JSON }}
      BUILD_OS: ${{ steps.set_outputs.outputs.BUILD_OS }}
      BUILD_BRANCH: ${{ steps.set_outputs.outputs.BUILD_BRANCH }}
      BUILD_TYPE: ${{ steps.set_outputs.outputs.BUILD_TYPE }}
    steps:

      - name: Capture start date and time
        id: start_time
        run: echo "start_time=$(date -u)" >> $GITHUB_ENV

      - name: Add start time to build_vars.json
        id: update_json
        run: |
          start_time=$(date -u)
          modified_json=$(echo '${{ inputs.BUILD_VARS_JSON }}' | jq --arg start_time "$start_time" '.buildstats += { "i2util-start": $start_time }')

          # Compact JSON for env file
          compact_json=$(echo "$modified_json" | jq -c '.')

          echo "BUILD_VARS_JSON=$compact_json" >> $GITHUB_ENV
          echo "::set-output name=BUILD_VARS_JSON::$compact_json"

      - name: Extract build vars and set outputs
        id: set_outputs
        run: |
          BUILD_VARS_JSON="${{ steps.update_json.outputs.BUILD_VARS_JSON }}"
          BUILD_OS=$(echo "$BUILD_VARS_JSON" | jq -r '.buildstats.OS')
          BUILD_BRANCH=$(echo "$BUILD_VARS_JSON" | jq -r '.buildstats.BUILD_BRANCH')
          BUILD_TYPE=$(echo "$BUILD_VARS_JSON" | jq -r '.buildstats.BUILD_TYPE')

          echo "::set-output name=BUILD_VARS_JSON::$BUILD_VARS_JSON"
          echo "::set-output name=BUILD_OS::$BUILD_OS"
          echo "::set-output name=BUILD_BRANCH::$BUILD_BRANCH"
          echo "::set-output name=BUILD_TYPE::$BUILD_TYPE"

          echo "BUILD_OS=$BUILD_OS" >> $GITHUB_ENV
          echo "BUILD_BRANCH=$BUILD_BRANCH" >> $GITHUB_ENV
          echo "BUILD_TYPE=$BUILD_TYPE" >> $GITHUB_ENV

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BUILD_BRANCH }}
