name: 'Issue States'

on:
  project_card:
    types: [created, edited, moved]

permissions:
  repository-projects: read
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/issue-states@v3
        with:
          github-token: ${{ secrets.PAT_PROJECT_PS_AUTO_ADD }}
          open-issue-columns: 'Ready, In Progress, Blocked, In Review'
          closed-issue-columns: 'Closed, Done'
          log-output: false
