name: Reusable Workflow

on:
  workflow_call:
    inputs:
      input_string:
        required: true
        type: string
      buildos_string:
        required: true
        type: string
    outputs:
      result:
        description: "The modified string"
        value: ${{ jobs.append-string.outputs.result }}

jobs:
  append-string:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.append.outputs.result }}
    steps:
      - id: append
        run: |
          new_value="${{ inputs.input_string }} likes cats"
          new_os="el9"
          echo "result=$new_value" >> $GITHUB_OUTPUT
          echo "work_os=$new_os" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

          
        



