name: Reusable Workflow

on:
  workflow_call:
    inputs:
      BUILD_VARS_JSON:  
        required: true
        type: string 
    outputs:
      BUILD_OS:
        description: "Build OS"
        value: ${{ jobs.add-one.outputs.BUILD_OS }} 
      BUILD_BRANCH:
        description: "BUILD BRANCH"
        value: ${{ jobs.add-one.outputs.BUILD_BRANCH }}
      BUILD_TYPE:
        description: "BUILD TYPE"
        value: ${{ jobs.add-one.outputs.BUILD_TYPE }}
      BUILD_VARS_JSON:
        description: "BUILD JSON FILE"
        value: ${{ jobs.add-one.outputs.BUILD_VARS_JSON }}

jobs:
  add-one:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.add.outputs.result }}
      BUILD_OS: ${{ steps.extract-build-vars.outputs.BUILD_OS }}
      BUILD_BRANCH: ${{ steps.extract-build-vars.outputs.BUILD_BRANCH }}
      BUILD_TYPE: ${{ steps.extract-build-vars.outputs.BUILD_TYPE }}
      BUILD_VARS_JSON: ${{ steps.modify_json.outputs.BUILD_VARS_JSON }}
      
    steps:

      - name: Echo BUILD_VARS_JSON
        run: |
          echo "BUILD_VARS_JSON is: ${{ inputs.BUILD_VARS_JSON }}"
          
      - name: Get build vars from input file
        id: extract-build-vars
        run: |
          echo '${{ inputs.BUILD_VARS_JSON }}' > input.json
          BUILD_OS=$(jq -r '.buildstats.OS' input.json)
          BUILD_BRANCH=$(jq -r '.buildstats.BUILD_BRANCH' input.json)
          BUILD_TYPE=$(jq -r '.buildstats.BUILD_TYPE' input.json)
          echo "** echo results **"
          echo "BUILD_OS=$BUILD_OS"
          echo "BUILD_BRANCH=$BUILD_BRANCH"
          echo "BUILD_TYPE=$BUILD_TYPE" 
          echo " ******************"
          echo "BUILD_OS=$BUILD_OS" >> $GITHUB_OUTPUT
          echo "BUILD_BRANCH=$BUILD_BRANCH" >> $GITHUB_OUTPUT
          echo "BUILD_TYPE=$BUILD_TYPE" >> $GITHUB_OUTPUT
          
      - name: Delete current repo from build
        id: modify_json
        run: |
         echo '${{ inputs.BUILD_VARS_JSON }}' > input.json
         modified_json=$(jq 'del(.repos[0])' input.json)
         BUILD_VARS_JSON=$(echo "$modified_json" | jq -c '.')
         echo "BUILD_VARS_JSON=$BUILD_VARS_JSON" >> $GITHUB_OUTPUT
         echo "**** next next ****"
         echo "BUILD_VARS_JSON=$BUILD_VARS_JSON"
         
      - name: Add GitHub run ID to buildids
        id: add_run_id
        run: |
         GITHUB_RUN_ID=${{ github.run_id }}
         REPO_NAME=${{ github.event.repository.name }}
    
         echo '${{ inputs.BUILD_VARS_JSON }}' > input.json

         # Properly read the contents of the file, not just echoing its name
         modified_json=$(jq --arg run_id "$GITHUB_RUN_ID" --arg repo "$REPO_NAME" '.buildids[$repo] = $run_id' input.json)

         # Compact the JSON
         BUILD_VARS_JSON=$(echo "$modified_json" | jq -c '.')

         # Save as a job output
         echo "build_vars_json=$BUILD_VARS_JSON" >> $GITHUB_OUTPUT

         # Print to logs for visibility
         echo "BUILD_VARS_JSON=$BUILD_VARS_JSON"


      
