name: Reusable Workflow

on:
  workflow_call:
    inputs:
      input_number:
        required: true
        type: number 
      BUILD_VARS_JSON:
        required: true
        type: string
    outputs:
      result:
        description: "Result after adding 1"
        value: ${{ jobs.add-one.outputs.result }}
      op:
        description: "OS version to build"
        value: ${{ jobs.add-one.outputs.op }}

jobs:
  add-one:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.add.outputs.result }}
      op: ${{ steps.add.outputs.op }}
    steps:
      - id: add
        run: |
          result=$(( ${{ inputs.input_number }} + 1 ))
          echo "result=$result" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Echo BUILD_VARS_JSON
        run: |
          echo "BUILD_VARS_JSON is: ${{ inputs.BUILD_VARS_JSON }}"

      - name: Get build vars from input file
        id: extract-build-vars
        run: |
          op="el9"
          echo "op=$op" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
          ##op=$(echo  '${{ inputs.BUILD_VARS_JSON }}' | jq -r '.buildstats.OS' )

          
        



