name: Reusable Workflow

on:
  workflow_call:
    inputs:
      BUILD_VARS_JSON:
        required: true
        type: string

jobs:
  echo-json:
    runs-on: ubuntu-latest
    steps:
      - name: Echo BUILD_VARS_JSON
        run: echo "BUILD_VARS_JSON is: ${{ inputs.BUILD_VARS_JSON }}"
