name: Reusable Workflow

on:
  workflow_call:
    inputs:
      BUILD_VARS_JSON:
        required: true
        type: string
    outputs:
      result:
        description: "Result after adding 7"
        value: ${{ jobs.add-one.outputs.result }}

jobs:
  add-one:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.add.outputs.result }}
    steps:
      - id: add
        run: |
          result=$(( ${{ inputs.input_number }} + 7 ))
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Echo BUILD_VARS_JSON
        run: |
          echo "BUILD_VARS_JSON is: ${{ inputs.BUILD_VARS_JSON }}"
          

      - name: Get build vars from input file
        id: extract-build-vars
        run: |
          echo '${{ inputs.BUILD_VARS_JSON }}' > input.json
          BUILD_OS=$(jq -r '.buildstats.OS' input.json)
          echo "BUILD_OS=$BUILD_OS"
          echo "BUILD_OS=$BUILD_OS" >> $GITHUB_OUTPUT

      
