name: Reusable Workflow

on:
  workflow_call:
    inputs:
      input_number:
        required: true
        type: number
      BUILD_VARS_JSON:
        required: true
        type: string
    outputs:
      result:
        description: "Result after adding 1"
        value: ${{ jobs.add-one.outputs.result }}
      BUILD_OS:
        description: "OS version to build"
        value: ${{ jobs.add-one.outputs.BUILD_OS }}

jobs:
  add-one:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.add.outputs.result }}
      BUILD_OS: ${{ steps.add.outputs.BUILD_OS }}
    steps:
      - id: add
        run: |
          result=$(( ${{ inputs.input_number }} + 1 ))
          echo "result=$result" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Echo BUILD_VARS_JSON
        run: |
          echo "BUILD_VARS_JSON is: ${{ inputs.BUILD_VARS_JSON }}"

      - name: Get build vars from input file
        id: extract-build-vars
        run: |
          BUILD_OS=$(echo  '${{ inputs.BUILD_VARS_JSON }}' | jq -r '.buildstats.OS' )
          echo "lets see results"
          echo "BUILD_OS=$BUILD_OS"
          echo "check github output"
          echo "BUILD_OS=$BUILD_OS" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
        #  echo "BUILD_OS=$BUILD_OS" >> $GITHUB_ENV 
        #  echo "BUILD_OS=$BUILD_OS"
          
        



