name: test-push-artifacts-workflow

on:
  push:
    branches: 
      - master 
env:  
  BUILD_OS: el9 

jobs:
  test-push-artifacts-workflow:
    runs-on: ubuntu-latest 

    steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Create and Upload Artifact
         run: |
           mkdir -p artifact
           echo "This is a test file" > artifact/test.txt
           cat artifact/test.txt
           
       - name: Set up SSH
         run: |
            mkdir -p ~/.ssh
            cat > ~/.ssh/id_rsa <<EOF
            ${{ secrets.SERVER_SSH_KEY }}
            EOF
            chmod 600 ~/.ssh/id_rsa
 
       - name: Copy artifact to server
         run: |
           scp ./artifact/test.txt ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/
 
       
