name: test-push-artifacts-workflow

on:
  push:
    branches: 
      - master 
env: 
  BUILD_OS: el8

jobs: 
  test-push-artifacts-workflow:
    runs-on: ubuntu-latest 

    steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Create and Upload Artifact
         run: |
           mkdir -p artifact
           echo "This is rsync test file" > artifact/test.txt
       - name: Copy artifact to server
         run: |
            case "${{ env.BUILD_OS }}" in
            'ol8'|'el9')
              if [ "${{ env.BUILD_OS }}" = "ol8" ]; then
                el_version="el8"
                OS_DIR="el8"
             else
               el_version="el9"
             fi  
             ;;
            'd11'|'d12'|'u20'|'u22'|'u24')  
              echo "deb ubuntu"
            ;;
            esac 
            echo "what version $el_version"
 
       
       
