name: test-push-artifacts-workflow

on:
  push:
    branches: 
      - master 
env: 
  BUILD_OS: el9  

jobs: 
  test-push-artifacts-workflow:
    runs-on: ubuntu-latest 

    steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Create and Upload Artifact
         run: |
           mkdir -p artifact
           echo "This is rsync test file" > artifact/test.txt
 
       
       
