name: test-push-artifacts-workflow

on:
  push:
    branches: 
      - master
env:  
  BUILD_OS: el9 

jobs:
  test-push-artifacts-workflow:
    runs-on: ubuntu-latest

    steps:

       - name: Set up SSH
         run: |
           ls
           mkdir -p artifacts
           ls
 
      
