name: test-push-artifacts-workflow

on:
  push:
    branches: 
      - master
env:  
  BUILD_OS: el9 

jobs:
  test-push-artifacts-workflow:
    runs-on: ubuntu-latest 

    steps:

       - name: Set up SSH
         run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            cat  ~/.ssh/id_rsa
            mkdir -p artifact
            echo "test" > ./artifact-folder/test
            cat ./artifact-folder/test

       - name: Copy artifact to server
         run: |
           scp -r ./artifact-folder/test ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}://

       
